{% set version = "0.0.1" %}

package:
  name: pyutils
  version: {{ version }}

source:
  path: ../

build:
  number: 3
  
  entry_points:
    - get_space = pyutils.get_space:main
    - killprocs = pyutils.killprocs:main
    - run_shrink = pyutils.run_shrink:main
    - crossref = pyutils.crossref:main
    
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:

  build:
    - python
    - click
    - numpy
  
  host:
    - python
    - numpy

  run:
    - python
    - psutil
    - numpy
    - click

test:
  imports:
    - pyutils
  commands:
    - killprocs --help
    - crossref --help


about:
  home: https://github.com/phaustin/pythonlibs
  license: LICENSE.txt
  license_family: BSD

  summary: 'general utilities'

extra:
  recipe-maintainers:
    - phaustin
