package:
  name: pyutils
  version: 0.1
  
source:
  path: ../

build:
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    
about:
  summary: 'pure python utilities'
  description: 'pure python utilities'

extra:
  recipe-maintainers:
    - phaustin

