git add -f CaseName
git add -f Makefile
git add -f Build
git add -f GATE/grd
git add -f GATE/grd_PB
git add -f GATE/GATE3h.nc
git add -f GATE/rad
git add -f GATE/snd
git add -f GATE/READ.ME
git add -f GATE/sfc
git add -f GATE/lst
git add -f GATE/lsf
git add -f GATE/trc
git add -f GATE/prm
git add -f python/add_rm.py
git add -f python/overwrite.sh
git add -f python/git_add.sh
git add -f python/copy.sh
git add -f python/remove.sh
git add -f python/initial_checkin.py
git add -f python/confirm_trans.py
git add -f SMOKE/grd
git add -f SMOKE/snd
git add -f SMOKE/lst
git add -f SMOKE/prm
git add -f TOGA/grd
git add -f TOGA/grd_PB
git add -f TOGA/plot_evol.ncl
git add -f TOGA/snd
git add -f TOGA/READ.ME
git add -f TOGA/sfc
git add -f TOGA/lst
git add -f TOGA/grd_std
git add -f TOGA/lsf
git add -f TOGA/grd_128
git add -f TOGA/trc
git add -f TOGA/toga_coare.nc
git add -f TOGA/prm
git add -f GABLS/grd
git add -f GABLS/snd
git add -f GABLS/READ.ME
git add -f GABLS/sfc
git add -f GABLS/lst
git add -f GABLS/trc
git add -f GABLS/prm
git add -f SRC/forcing.f90
git add -f SRC/shear_prod3D.f90
git add -f SRC/utils.f90
git add -f SRC/setdata.f90
git add -f SRC/stat_sw2.f90
git add -f SRC/printout.f90
git add -f SRC/setforcing.f90
git add -f SRC/write_fields3D.f90
git add -f SRC/task_util_MPI.f90
git add -f SRC/task_bound_duvdt.f90
git add -f SRC/movies.f90
git add -f SRC/stat_mom.f90
git add -f SRC/pressz.f90
git add -f SRC/fft.f
git add -f SRC/hbuf_micro_init.f90
git add -f SRC/header.f90
git add -f SRC/uvw.f90
git add -f SRC/task_rank_to_index.f90
git add -f SRC/init.f90
git add -f SRC/precip_fall.f90
git add -f SRC/nudging.f90
git add -f SRC/advect_scalar3D.f90
git add -f SRC/adams.f90
git add -f SRC/random.f90
git add -f SRC/diagnose.f90
git add -f SRC/sat.f90
git add -f SRC/advect2_mom_z.f90
git add -f SRC/diffuse_mom3D.f90
git add -f SRC/kurant.f90
git add -f SRC/isccpSimulator.f90
git add -f SRC/task_assign_bnd.f90
git add -f SRC/task_exchange.f90
git add -f SRC/stat_moments.f90
git add -f SRC/task_util_NOMPI.f9000
git add -f SRC/subsidence.f90
git add -f SRC/isccp.f90
git add -f SRC/upperbound.f90
git add -f SRC/tracers.f90
git add -f SRC/stat_sw1.f90
git add -f SRC/diffuse_mom.f90
git add -f SRC/isccpHistograms.f90
git add -f SRC/rad_simple_smoke.f90
git add -f SRC/abcoefs.f90
git add -f SRC/periodic.f90
git add -f SRC/press_rhs.f90
git add -f SRC/advect_mom.f90
git add -f SRC/task_ranks.f90
git add -f SRC/simple_ocean.f90
git add -f SRC/diffuse_scalar3D.f90
git add -f SRC/bound_exchange.f90
git add -f SRC/shear_prod2D.f90
git add -f SRC/statistics.f90
git add -f SRC/grid.f90
git add -f SRC/ice_fall.f90
git add -f SRC/radiation.f90
git add -f SRC/cstuff.c
git add -f SRC/atmosphere.f90
git add -f SRC/params.f90
git add -f SRC/diffuse_scalar2D.f90
git add -f SRC/coriolis.f90
git add -f SRC/domain.f90
git add -f SRC/oceflx.f90
git add -f SRC/advect_scalar.f90
git add -f SRC/diffuse_scalar.f90
git add -f SRC/setparm.f90
git add -f SRC/advect_scalar2D.f90
git add -f SRC/bound_duvdt.f90
git add -f SRC/isccpDummy.f9000
git add -f SRC/task_init.f90
git add -f SRC/write_fields2D.f90
git add -f SRC/setperturb.f90
git add -f SRC/pressure.f90
git add -f SRC/damping.f90
git add -f SRC/stat_2Dinit.f90
git add -f SRC/pressure_big.f90
git add -f SRC/rad_simple.f90
git add -f SRC/zero.f90
git add -f SRC/restart.f90
git add -f SRC/main.f90
git add -f SRC/stat_precip.f90
git add -f SRC/diffuse_mom2D.f90
git add -f SRC/hbuf_conditionals_init.f90
git add -f SRC/stat_varscalar.f90
git add -f SRC/landflx.f90
git add -f SRC/surface.f90
git add -f SRC/readiopdata.f90
git add -f SRC/stat_tke.f90
git add -f SRC/stepout.f90
git add -f SRC/advect2_mom_xy.f90
git add -f SRC/tke_full.f90
git add -f SRC/pressure_orig.f90
git add -f SRC/press_grad.f90
git add -f SRC/._MICRO_M2005
git add -f SRC/hbuffer.f90
git add -f SRC/vars.f90
git add -f SRC/boundaries.f90
git add -f SRC/setgrid.f90
git add -f SRC/task_boundaries.f90
git add -f SRC/task_dispatch.f90
git add -f SRC/buoyancy.f90
git add -f SRC/compress3D.f90
git add -f SRC/MICRO_SAM1MOM/micro_params.f90
git add -f SRC/MICRO_SAM1MOM/microphysics.f90
git add -f SRC/MICRO_SAM1MOM/precip_init.f90
git add -f SRC/MICRO_SAM1MOM/precip_proc.f90
git add -f SRC/MICRO_SAM1MOM/cloud.f90
git add -f SRC/TIMING/get_thread_num.c
git add -f SRC/TIMING/get_cpustamp.c
git add -f SRC/TIMING/README
git add -f SRC/TIMING/t_pclstr.c
git add -f SRC/TIMING/t_pr.c
git add -f SRC/TIMING/t_initialize.c
git add -f SRC/TIMING/t_stop.c
git add -f SRC/TIMING/t_setoption.c
git add -f SRC/TIMING/t_start.c
git add -f SRC/TIMING/t_reset.c
git add -f SRC/TIMING/t_error.c
git add -f SRC/TIMING/gpt.inc
git add -f SRC/TIMING/gpt.h
git add -f SRC/TIMING/cfort.h
git add -f SRC/TIMING/f_wrappers.c
git add -f SRC/TIMING/t_stamp.c
git add -f SRC/RAD_DUMMY/cldefrint.f
git add -f SRC/RAD_DUMMY/cldefr.f
git add -f SRC/RAD_DUMMY/dummy.f
git add -f SRC/RAD_DUMMY/rad_full.f
git add -f SRC/RAD_DUMMY/rad.f90
git add -f SRC/RAD_DUMMY/prgrid.h
git add -f SRC/MICRO_DRIZZLE/micro_params.f90
git add -f SRC/MICRO_DRIZZLE/microphysics.f90
git add -f SRC/MICRO_DRIZZLE/precip_init.f90
git add -f SRC/MICRO_DRIZZLE/precip_proc.f90
git add -f SRC/MICRO_DRIZZLE/cloud.f90
git add -f SRC/MICRO_DRIZZLE/README.MICRO_DRIZZLE
git add -f SRC/MICRO_TEMPLATE/microphysics.f90.template
git add -f SRC/RAD_CAM/rad_full.f90
git add -f SRC/RAD_CAM/gffgch.f90
git add -f SRC/RAD_CAM/rad_restart.f90
git add -f SRC/RAD_CAM/trcab.f90
git add -f SRC/RAD_CAM/radcswmx.f90
git add -f SRC/RAD_CAM/radoz2.f90
git add -f SRC/RAD_CAM/radini.f90
git add -f SRC/RAD_CAM/shr_orb_mod.f90
git add -f SRC/RAD_CAM/ppgrid.f90
git add -f SRC/RAD_CAM/volcrad.f90
git add -f SRC/RAD_CAM/traceini.f90
git add -f SRC/RAD_CAM/trcabn.f90
git add -f SRC/RAD_CAM/zenith.f90
git add -f SRC/RAD_CAM/trcpth.f90
git add -f SRC/RAD_CAM/aer_optics.f90
git add -f SRC/RAD_CAM/quicksort.f90
git add -f SRC/RAD_CAM/pkg_cldoptics.f90
git add -f SRC/RAD_CAM/trcplk.f90
git add -f SRC/RAD_CAM/radinp.f90
git add -f SRC/RAD_CAM/raddedmx.f90
git add -f SRC/RAD_CAM/cldefrint.f90
git add -f SRC/RAD_CAM/trcems.f90
git add -f SRC/RAD_CAM/radae.f90
git add -f SRC/RAD_CAM/albedo.f90
git add -f SRC/RAD_CAM/shr_kind_mod.f90
git add -f SRC/RAD_CAM/abortutils.f90
git add -f SRC/RAD_CAM/radclwmx.f90
git add -f SRC/RAD_CAM/rad.f90
git add -f SRC/RAD_CAM/wrap_nf.f90
git add -f SRC/SCRIPT/mkDepends
git add -f SRC/SCRIPT/mkSrcfiles
git add -f SRC/MICRO_M2005/microphysics.f90
git add -f SRC/MICRO_M2005/README.MICRO_M2005
git add -f SRC/MICRO_M2005/._CVS
git add -f SRC/MICRO_M2005/satadj_rational.f90
git add -f SRC/MICRO_M2005/module_mp_graupel.f90
git add -f SRC/MICRO_M2005/CVS
git add -f GCSSARM/grd
git add -f GCSSARM/snd
git add -f GCSSARM/sfc
git add -f GCSSARM/lst
git add -f GCSSARM/lsf
git add -f GCSSARM/prm
git add -f ARM9707/grd
git add -f ARM9707/grd_PB
git add -f ARM9707/grd_sp
git add -f ARM9707/rad
git add -f ARM9707/snd
git add -f ARM9707/grd_96
git add -f ARM9707/READ.ME
git add -f ARM9707/sfc
git add -f ARM9707/cldamount_arm9707.nc
git add -f ARM9707/lst
git add -f ARM9707/grd_sp30
git add -f ARM9707/grd_std
git add -f ARM9707/lsf
git add -f ARM9707/arm9707.nc
git add -f ARM9707/grd_128
git add -f ARM9707/trc
git add -f ARM9707/prm
git add -f DYCOMS_RF02/grd
git add -f DYCOMS_RF02/lsf.f
git add -f DYCOMS_RF02/S
git add -f DYCOMS_RF02/prm_big
git add -f DYCOMS_RF02/grd.f
git add -f DYCOMS_RF02/lsf_orig
git add -f DYCOMS_RF02/snd_orig
git add -f DYCOMS_RF02/snd
git add -f DYCOMS_RF02/sfc
git add -f DYCOMS_RF02/lst
git add -f DYCOMS_RF02/lsf_rev
git add -f DYCOMS_RF02/grd_orig
git add -f DYCOMS_RF02/snd_rev
git add -f DYCOMS_RF02/lsf
git add -f DYCOMS_RF02/prm_orig
git add -f DYCOMS_RF02/grd_rev
git add -f DYCOMS_RF02/snd.f
git add -f DYCOMS_RF02/prm
git add -f TOGA_LONG/grd
git add -f TOGA_LONG/grd_PB
git add -f TOGA_LONG/grd_sp
git add -f TOGA_LONG/prm_std
git add -f TOGA_LONG/README
git add -f TOGA_LONG/snd
git add -f TOGA_LONG/grd_96
git add -f TOGA_LONG/sfc
git add -f TOGA_LONG/lsf3D
git add -f TOGA_LONG/lst
git add -f TOGA_LONG/grd_sp30
git add -f TOGA_LONG/.DS_Store
git add -f TOGA_LONG/grd_std
git add -f TOGA_LONG/lsf
git add -f TOGA_LONG/lsf_hor
git add -f TOGA_LONG/trc
git add -f TOGA_LONG/toga_coare_long.nc
git add -f TOGA_LONG/prm
git add -f TOGA_LONG/._.DS_Store
git add -f BOMEX/grd
git add -f BOMEX/grd_PB
git add -f BOMEX/rad
git add -f BOMEX/grd_20m
git add -f BOMEX/snd
git add -f BOMEX/READ.ME
git add -f BOMEX/sfc
git add -f BOMEX/grd_40m
git add -f BOMEX/lst
git add -f BOMEX/lsf
git add -f BOMEX/trc
git add -f BOMEX/prm
git add -f Changes_log/Changes_6.6.5_to_6.7.3
git add -f Changes_log/Changes_6.6.5_to_6.6.5a
git add -f Changes_log/README.UUmods
git add -f Changes_log/README.UWmods_6.7
git add -f Changes_log/Changes_6.5_to_6.6
git add -f Changes_log/Changes_6.4_to_6.5
git add -f Changes_log/Changes_6.1_to_6.2
git add -f Changes_log/Changes_6.7.3_to_6.7.4
git add -f Changes_log/Changes_6.7.4_to_6.7.5
git add -f Changes_log/Changes_6.0_to_6.1
git add -f Changes_log/Changes_6.2_to_6.3
git add -f Changes_log/Changes_6.6_to_6.6.5
git add -f Changes_log/Changes_6.3_to_6.4
git add -f Changes_log/Changes_5_to_6
git add -f DOC/.DS_Store
git add -f DOC/SAM6.7_guide.doc
git add -f DOC/SAM6.7_guide.pdf
git add -f DOC/._.DS_Store
git add -f GATE_IDEAL/grd
git add -f GATE_IDEAL/rad
git add -f GATE_IDEAL/snd
git add -f GATE_IDEAL/sfc
git add -f GATE_IDEAL/lst
git add -f GATE_IDEAL/lsf
git add -f GATE_IDEAL/grd_128
git add -f GATE_IDEAL/grd_50-100-200
git add -f GATE_IDEAL/grd33
git add -f GATE_IDEAL/prm
git add -f GATE_IDEAL/noshear_normalf/grd
git add -f GATE_IDEAL/noshear_normalf/rad
git add -f GATE_IDEAL/noshear_normalf/snd
git add -f GATE_IDEAL/noshear_normalf/sfc
git add -f GATE_IDEAL/noshear_normalf/lsf
git add -f GATE_IDEAL/shear_normalf/grd
git add -f GATE_IDEAL/shear_normalf/rad
git add -f GATE_IDEAL/shear_normalf/snd
git add -f GATE_IDEAL/shear_normalf/sfc
git add -f GATE_IDEAL/shear_normalf/lsf
git add -f GATE_IDEAL/noshear_rlsf/grd
git add -f GATE_IDEAL/noshear_rlsf/rad
git add -f GATE_IDEAL/noshear_rlsf/snd
git add -f GATE_IDEAL/noshear_rlsf/sfc
git add -f GATE_IDEAL/noshear_rlsf/lsf
git add -f GATE_IDEAL/shear_varlsf/rad
git add -f GATE_IDEAL/shear_varlsf/snd
git add -f GATE_IDEAL/shear_varlsf/lsf
git add -f GATE_IDEAL/shear_rlsf/grd
git add -f GATE_IDEAL/shear_rlsf/rad
git add -f GATE_IDEAL/shear_rlsf/snd
git add -f GATE_IDEAL/shear_rlsf/sfc
git add -f GATE_IDEAL/shear_rlsf/lsf
git add -f GATE_IDEAL/noshear_varlsf/rad
git add -f GATE_IDEAL/noshear_varlsf/snd
git add -f GATE_IDEAL/noshear_varlsf/lsf
git add -f RUNDATA/READ.ME
git add -f RUNDATA/isccp
git add -f RUNDATA/AerosolOptics_c040105.nc
git add -f RUNDATA/abs_ems_factors_fastvx.c030508.nc
git add -f DYCOMS_RF01/grd
git add -f DYCOMS_RF01/snd
git add -f DYCOMS_RF01/READ.ME
git add -f DYCOMS_RF01/sfc
git add -f DYCOMS_RF01/lst
git add -f DYCOMS_RF01/.DS_Store
git add -f DYCOMS_RF01/lsf
git add -f DYCOMS_RF01/prm
git add -f DYCOMS_RF01/._.DS_Store
git add -f ASTEX209/grd
git add -f ASTEX209/snd
git add -f ASTEX209/READ.ME
git add -f ASTEX209/sfc
git add -f ASTEX209/lst
git add -f ASTEX209/lsf
git add -f ASTEX209/trc
git add -f ASTEX209/prm
git add -f UTIL/Makefile
git add -f UTIL/SRC/sat.f
git add -f UTIL/SRC/hbuf_lib.f
git add -f UTIL/SRC/bin2D2nc.f
git add -f UTIL/SRC/2Dbin2nc.f
git add -f UTIL/SRC/bin3D2nc_mean.f
git add -f UTIL/SRC/2Dbin2nc_sep.f
git add -f UTIL/SRC/2Dbin_sep2one.f
git add -f UTIL/SRC/dat3D2nc_shifted.f
git add -f UTIL/SRC/hbuf.inc
git add -f UTIL/SRC/cape.f
git add -f UTIL/SRC/com2D2nc.f
git add -f UTIL/SRC/stat2evol.f.old
git add -f UTIL/SRC/bin3D_sep2one.f
git add -f UTIL/SRC/cup.h
git add -f UTIL/SRC/cin_orig.f
git add -f UTIL/SRC/bin3D2nc.f
git add -f UTIL/SRC/dat3D2nc_mean.f
git add -f UTIL/SRC/2Dcom2nc_sep.f
git add -f UTIL/SRC/2Dcom_sep2one.f
git add -f UTIL/SRC/2Dcom2nc_mean.f
git add -f UTIL/SRC/stat2nc_sp.f
git add -f UTIL/SRC/com3D2nc_mean.f
git add -f UTIL/SRC/stat2nc.f
git add -f UTIL/SRC/com3D2bin.f
git add -f UTIL/SRC/com3D2nc_sep.f
git add -f UTIL/SRC/stat2evol.f
git add -f UTIL/SRC/2Ddat2nc_mean.f
git add -f UTIL/SRC/isccp2nc.f
git add -f UTIL/SRC/statistics.f
git add -f UTIL/SRC/cape_analysis.f
git add -f UTIL/SRC/dat2D2nc.f
git add -f UTIL/SRC/evol2nc.f
git add -f UTIL/SRC/2Dbin2nc_mean.f
git add -f UTIL/SRC/com3D2nc.f
git add -f UTIL/SRC/dat3D2nc.f
git add -f UTIL/SRC/z2pres.f
git add -f UTIL/SRC/pres2z.f
git add -f UTIL/SRC/stat2evolnc.f
git add -f UTIL/SRC/stat2nc_rp.f90
git add -f UTIL/SRC/2Dcom2nc.f
git add -f UTIL/SRC/cupmcb.f
git add -f UTIL/SRC/com3D_sep2one.f
git add -f UTIL/SRC/cin.f
git add -f UTIL/SRC/2Ddat2nc.f
git add -f UTIL/SRC/hbuffer.f90
git add -f UTIL/SRC/cape_orig.f
git add -f KWAJEX/grd
git add -f KWAJEX/grd_PB
git add -f KWAJEX/snd
git add -f KWAJEX/grd_96
git add -f KWAJEX/sfc
git add -f KWAJEX/lsf3D
git add -f KWAJEX/lst
git add -f KWAJEX/lsf
git add -f KWAJEX/lsf_hor
git add -f KWAJEX/trc
git add -f KWAJEX/kwajex.nc
git add -f KWAJEX/prm
git add -f ARM0003/grd
git add -f ARM0003/snd
git add -f ARM0003/READ.ME
git add -f ARM0003/sfc
git add -f ARM0003/lst
git add -f ARM0003/lsf
git add -f ARM0003/trc
git add -f ARM0003/prm
git add -f LBA/grd
git add -f LBA/grd_PB
git add -f LBA/grd.f
git add -f LBA/rad
git add -f LBA/snd
git add -f LBA/READ.ME
git add -f LBA/sfc
git add -f LBA/lst
git add -f LBA/grd_std
git add -f LBA/grd_128
git add -f LBA/grd_50-100-200
git add -f LBA/trc
git add -f LBA/prm_100m
git add -f LBA/grd_100m
git add -f LBA/a.out
git add -f LBA/prm
git add -f SCRIPTS/rm_some.csh
git add -f SCRIPTS/scp_com3D_all.csh
git add -f SCRIPTS/number
git add -f SCRIPTS/scp_moments_com3D_all.csh
git add -f SCRIPTS/image.sgi
git add -f SCRIPTS/com3D_moments_sep2one_all.csh
git add -f SCRIPTS/com3D_sep2one_all.csh
git add -f SCRIPTS/rm_some_2Dcom.csh
git add -f SCRIPTS/2Dcom2nc_all.csh
git add -f SCRIPTS/see_all.csh
git add -f SCRIPTS/com3D2nc_all.csh
git add -f SCRIPTS/glue_compile.csh
git add -f SCRIPTS/2Dcom_sep2one_all.csh
git add -f SCRIPTS/scp_2Dcom_all.csh
git add -f SCRIPTS/test.csh
git add -f SCRIPTS/raw2gif.csh
git add -f SCRIPTS/rm_all.csh
git add -f SCRIPTS/bin3D_sep2one_all.csh
git add -f SCRIPTS/2Dbin_sep2one_all.csh
git add -f SCRIPTS/glue_raw_mk.f90
git add -f SCRIPTS/repair.f90
git add -f SCRIPTS/makeframes.csh
git add -f SCRIPTS/NCL/ens_evol_ens1.ncl
git add -f SCRIPTS/NCL/plot_squall_xz.ncl
git add -f SCRIPTS/NCL/plot_frame_vort.ncl
git add -f SCRIPTS/NCL/plot_frame_clouds_mse.ncl
git add -f SCRIPTS/NCL/skewt_func.ncl
git add -f SCRIPTS/NCL/plot_time_cloud.ncl
git add -f SCRIPTS/NCL/plot_tke_budget.ncl
git add -f SCRIPTS/NCL/plot_frame.ncl
git add -f SCRIPTS/NCL/ens_evol_ens.ncl
git add -f SCRIPTS/NCL/stat_out.ncl
git add -f SCRIPTS/NCL/plot_frame_mse.ncl
git add -f SCRIPTS/NCL/plot_time_sfcfluxes.ncl
git add -f SCRIPTS/NCL/plot_forcing.ncl
git add -f SCRIPTS/NCL/conv_analysis_rho.ncl
git add -f SCRIPTS/NCL/plot_frame_div.ncl
git add -f SCRIPTS/NCL/frameit.ncl
git add -f SCRIPTS/NCL/conv_analysis_rho1.ncl
git add -f SCRIPTS/NCL/plot_frame_clouds.ncl
git add -f SCRIPTS/NCL/plot_sounding.ncl
git add -f SCRIPTS/NCL/tmp.ncl
git add -f SCRIPTS/NCL/plot_profile.ncl
git add -f SCRIPTS/NCL/budget_water_subperiod.ncl
git add -f SCRIPTS/NCL/plot_pdf_cwp.ncl
git add -f SCRIPTS/NCL/conv_mom_trans.ncl
git add -f SCRIPTS/NCL/open_wks.ncl
git add -f SCRIPTS/NCL/budget_water.ncl
git add -f SCRIPTS/NCL/plot_sounding3.ncl
git add -f SCRIPTS/NCL/plot_sounding_all.ncl
git add -f SCRIPTS/NCL/plot_field.ncl
git add -f SCRIPTS/NCL/plot_profile_cases_diffz.ncl
git add -f SCRIPTS/NCL/plot_profile_cases.ncl
git add -f SCRIPTS/NCL/skewt_func_new.ncl
git add -f SCRIPTS/NCL/extract.ncl
git add -f SCRIPTS/NCL/skewt_func_mod.ncl
git add -f SCRIPTS/NCL/plotXYmarker.ncl
git add -f SCRIPTS/NCL/plot_frame_xz.ncl
git add -f SCRIPTS/NCL/plot_time_z.ncl
git add -f SCRIPTS/NCL/plot_buoya.ncl
git add -f SCRIPTS/NCL/plot_time_z_pbl.ncl
git add -f SCRIPTS/NCL/ARCHIVE/ens_evol_ens1.ncl
git add -f SCRIPTS/NCL/ARCHIVE/plot_frame_clouds_mse.ncl
git add -f SCRIPTS/NCL/ARCHIVE/skewt_func.ncl
git add -f SCRIPTS/NCL/ARCHIVE/plot_time_cloud.ncl
git add -f SCRIPTS/NCL/ARCHIVE/plot_tke_budget.ncl
git add -f SCRIPTS/NCL/ARCHIVE/plot_frame.ncl
git add -f SCRIPTS/NCL/ARCHIVE/ens_evol_ens.ncl
git add -f SCRIPTS/NCL/ARCHIVE/stat_out.ncl
git add -f SCRIPTS/NCL/ARCHIVE/plot_frame_mse.ncl
git add -f SCRIPTS/NCL/ARCHIVE/plot_time_sfcfluxes.ncl
git add -f SCRIPTS/NCL/ARCHIVE/plot_forcing.ncl
git add -f SCRIPTS/NCL/ARCHIVE/conv_analysis_rho.ncl
git add -f SCRIPTS/NCL/ARCHIVE/frameit.ncl
git add -f SCRIPTS/NCL/ARCHIVE/conv_analysis_rho1.ncl
git add -f SCRIPTS/NCL/ARCHIVE/plot_frame_clouds.ncl
git add -f SCRIPTS/NCL/ARCHIVE/plot_sounding.ncl
git add -f SCRIPTS/NCL/ARCHIVE/tmp.ncl
git add -f SCRIPTS/NCL/ARCHIVE/plot_profile.ncl
git add -f SCRIPTS/NCL/ARCHIVE/budget_water_subperiod.ncl
git add -f SCRIPTS/NCL/ARCHIVE/conv_mom_trans.ncl
git add -f SCRIPTS/NCL/ARCHIVE/open_wks.ncl
git add -f SCRIPTS/NCL/ARCHIVE/budget_water.ncl
git add -f SCRIPTS/NCL/ARCHIVE/plot_sounding3.ncl
git add -f SCRIPTS/NCL/ARCHIVE/plot_sounding_all.ncl
git add -f SCRIPTS/NCL/ARCHIVE/plot_field.ncl
git add -f SCRIPTS/NCL/ARCHIVE/skewt_func_new.ncl
git add -f SCRIPTS/NCL/ARCHIVE/extract.ncl
git add -f SCRIPTS/NCL/ARCHIVE/skewt_func_mod.ncl
git add -f SCRIPTS/NCL/ARCHIVE/plotXYmarker.ncl
git add -f SCRIPTS/NCL/ARCHIVE/plot_time_z.ncl
git add -f SCRIPTS/NCL/ARCHIVE/plot_buoya.ncl
git add -f SCRIPTS/NCL/ARCHIVE/plot_time_z_pbl.ncl
