cp -af /home/phil/repos/sam_orig/SAM6.9.6/UTIL/SRC/glue_movie_raw.f /home/phil/repos/sam_orig/tesp/UTIL/SRC/glue_movie_raw.f
git add -f UTIL/SRC/glue_movie_raw.f
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/domain.f90 /home/phil/repos/sam_orig/tesp/SRC/domain.f90
git add -f SRC/domain.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/adams.f90 /home/phil/repos/sam_orig/tesp/SRC/adams.f90
git add -f SRC/adams.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/press_grad.f90 /home/phil/repos/sam_orig/tesp/SRC/press_grad.f90
git add -f SRC/press_grad.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/UTIL/Makefile /home/phil/repos/sam_orig/tesp/UTIL/Makefile
git add -f UTIL/Makefile
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/diagnose.f90 /home/phil/repos/sam_orig/tesp/SRC/diagnose.f90
git add -f SRC/diagnose.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/setdata.f90 /home/phil/repos/sam_orig/tesp/SRC/setdata.f90
git add -f SRC/setdata.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/surface.f90 /home/phil/repos/sam_orig/tesp/SRC/surface.f90
git add -f SRC/surface.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/write_fields3D.f90 /home/phil/repos/sam_orig/tesp/SRC/write_fields3D.f90
git add -f SRC/write_fields3D.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/stepout.f90 /home/phil/repos/sam_orig/tesp/SRC/stepout.f90
git add -f SRC/stepout.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/main.f90 /home/phil/repos/sam_orig/tesp/SRC/main.f90
git add -f SRC/main.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/task_init.f90 /home/phil/repos/sam_orig/tesp/SRC/task_init.f90
git add -f SRC/task_init.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/header.f90 /home/phil/repos/sam_orig/tesp/SRC/header.f90
git add -f SRC/header.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/TOGA/prm /home/phil/repos/sam_orig/tesp/TOGA/prm
git add -f TOGA/prm
cp -af /home/phil/repos/sam_orig/SAM6.9.6/DOC/SAM6.9_guide.pdf /home/phil/repos/sam_orig/tesp/DOC/SAM6.9_guide.pdf
git add -f DOC/SAM6.9_guide.pdf
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/utils.f90 /home/phil/repos/sam_orig/tesp/SRC/utils.f90
git add -f SRC/utils.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/GATE_IDEAL/prm /home/phil/repos/sam_orig/tesp/GATE_IDEAL/prm
git add -f GATE_IDEAL/prm
cp -af /home/phil/repos/sam_orig/SAM6.9.6/./Makefile /home/phil/repos/sam_orig/tesp/./Makefile
git add -f ./Makefile
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/grid.f90 /home/phil/repos/sam_orig/tesp/SRC/grid.f90
git add -f SRC/grid.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/landflx.f90 /home/phil/repos/sam_orig/tesp/SRC/landflx.f90
git add -f SRC/landflx.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/movies.f90 /home/phil/repos/sam_orig/tesp/SRC/movies.f90
git add -f SRC/movies.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/MICRO_M2005/microphysics.f90 /home/phil/repos/sam_orig/tesp/SRC/MICRO_M2005/microphysics.f90
git add -f SRC/MICRO_M2005/microphysics.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/RAD_CAM/rad_restart.f90 /home/phil/repos/sam_orig/tesp/SRC/RAD_CAM/rad_restart.f90
git add -f SRC/RAD_CAM/rad_restart.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/SRC/vars.f90 /home/phil/repos/sam_orig/tesp/SRC/vars.f90
git add -f SRC/vars.f90
cp -af /home/phil/repos/sam_orig/SAM6.9.6/DOC/SAM6.9_guide.doc /home/phil/repos/sam_orig/tesp/DOC/SAM6.9_guide.doc
git add -f DOC/SAM6.9_guide.doc
